# Generated by Django 3.2.3 on 2021-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('num_boleta', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre_pro', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precio', models.CharField(default='DEFAULT VALUE', max_length=20)),
                ('stock', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_cl', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('direccion', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('boletas', models.ManyToManyField(to='boleta.Boleta')),
                ('productos', models.ManyToManyField(to='boleta.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.ManyToManyField(to='boleta.Producto'),
        ),
    ]
