# Generated by Django 3.1.2 on 2021-06-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
