# Generated by Django 3.1.2 on 2021-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cl',
            field=models.CharField(max_length=100, verbose_name='Rut Cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_pro',
            field=models.CharField(max_length=100, verbose_name='Nombre Producto'),
        ),
    ]
