# Generated by Django 3.2.3 on 2021-06-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='productos',
        ),
    ]
