# Generated by Django 3.1.2 on 2021-06-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='num_boleta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
