# Generated by Django 3.2.4 on 2021-06-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0003_auto_20210604_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
